#CircleCI configuration file

version: 2.1
orbs:
  android: circleci/android@2.0
jobs:
  build:
    docker:
      #- image: cimg/python:3.8 # the primary container, where your job's commands are run
      - image: cimg/android:2022.07
    steps:
      - checkout # check out the code in the project directory
      - run: sudo apt-get update
      - run: sudo rm /var/cache/apt/archives/lock
      - run: sudo rm /var/lib/dpkg/lock
      - run: sudo apt-get install -y nodejs
      - run: sudo node --version
      - run: sudo apt-get update
      - run: sudo node --version
      - run: sudo apt-get install -y npm
      - run: sudo npm --version
      - run: sudo apt-get update
      - run: sudo npm --version
      - run: sudo npm install appium
      - run: sudo apt-get install -y python3.10
      - run: sudo apt install -y python3-pip
      - run: sudo pip3 install Appium-Python-Client
      - run: sudo pip3 install pytest
      - run: echo $PATH
      - run: appium --address 127.0.0.1 --port 4723
      - run: python3 -m pytest "AppiumTest.py"