#CircleCI configuration file

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.07 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - python/install-packages:
          pkg-manager: pip

      - run: python -m pytest "AppiumTest.py"