#CircleCI configuration file

version: 2.1
orbs:
  android: circleci/android@2.0
jobs:
  build:
    docker:
      #- image: cimg/python:3.8 # the primary container, where your job's commands are run
      - image: cimg/android:2022.07
    steps:
      - checkout # check out the code in the project directory
      - run: cd /
      - run: apt install nodejs
      - run: apt install npm
      - run: npm install -g appium
      - run: pip install Appium-Python-Client
      - run: pip install pytest
      - run: python -m pytest "AppiumTest.py"